Updated TinyWebDB files
Kodular/TinyWebDB pull request #2
Opened 2018-01-23 10:11 UTC by Kanishka-Developer

These files are updated for the latest changes to Google Cloud Platform.
These are not to be merged - these files are meant to _replace_ the existing files.
I also edited the index.html file to be more Makeroid-ish.
For any queries or whatever, contact me by email. (kanishka.developer@gmail.com)

2018-01-23 10:40 UTC, pavi2410 commented
I just started to work on it, thinking of using Flask. I have already done many changes which will create merge conflicts.

My changes are here: github.com/pavi2410/TinyWebDB

2018-01-23 14:37 UTC, Kanishka-Developer commented
@pavi2410 The only files I actually edited are app.yaml and index.html.
Can you pull index.html (along with the images)?

2018-01-23 16:58 UTC, barreeeiroo requested changes

2018-01-23 16:58 UTC, barreeeiroo commented on README.md
> +# TinyWebDB (Updated)
Remove the (Updated) here and set `Makeroid TinyWebDB`

2018-01-23 16:58 UTC, barreeeiroo commented on README.md
> +Updated TinyWebDB service for Makeroid
Here remove the `Updated `

2018-01-23 17:34 UTC, Kanishka-Developer commented
Done, @barreeeiroo.

2018-01-27 02:49 UTC, Kanishka-Developer commented
@pavi2410 @barreeeiroo Anything else?

2018-02-03 15:55 UTC, barreeeiroo approved these changes

2018-02-03 15:57 UTC, merged